### ISSUE TITLE
Please publish release with django 1.7+ support

### ISSUE THREAD

**Issue by dionorgua** [beanbaginc/django-evolution#4]
Hi,

As far as I see, git repo already supports recent versions of django. Could you please release it as something like 0.6.8?

It'll simplify things for distributions. Otherwise I'll need to fix debian package by upload something like 0.6.7+git20160728

Thanks!

**Comment by chipx86** [comment]
The changes that have gone in for Django 1.7+ support doesn't actually make Django Evolution truly compatible with 1.7+. It fixes up things so that in a test environment, or when imported/basic function run, it will work against the modern API. That's a far cry from working alongside Django 1.7+'s mutations support, which is a whole separate body of work that is planned but far from release.

This work is extremely non-trivial. There won't be any releases by us in the near-future (and we'd ask you not to release any) that advertises Django 1.7+ support. It would just break people.

**Comment by dionorgua** [comment]
Ok.. Thanks for your details. and warning!

debian switched to django 1.7. And django_evolution fails to build with it:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755594

So I can't stay with 0.6.7 at all. It should be either fixed or removed from debian. What you suggest to do?
1. Just prepare 0.6.7-2 debian package with applied patch (it'll build fine and passes tests)
2. Remove package from debian until it's fixed.

Thanks a lot!

**Comment by chipx86** [comment]
So, a large part of why we continue to maintain Django Evolution, instead of relying on Django 1.7's migrations, is because we develop Review Board, and this also depends on Django 1.6 (again, for many many _many_ compatibility reasons -- each new release of Django introduces substantial breaking changes, which is bad for us and our customers).

Whatever decision impacts Django Evolution will no doubt impact Review Board as well (assuming Review Board is being packaged in Debian).

Option #1 would do nothing other than create confusion at this point. We _do_ want to ship a build that provides build-time compatibility with Django 1.6 through 1.9, but we're not ready to do that yet. Having one in the wild would likely just create support issues for us (when you're dealing with database migrations, it's crucial that these things work before they get into others' hands).

Option #2 might be your only option for now, which is really a shame.

What about Option #3: Don't include an actual dependency on a Django package. Make sure the package description works only with Django 1.4 through 1.6. If someone is installing Django Evolution. If a package needs it, then it's likely using Django 1.6 anyway. If a developer needs it, they're also handling their Django dependency anyway. It's highly unlikely any project out there is using Django Evolution as a gateway to their Django dependency (which would be dangerous and unpredictable).

This way, the package can remain in Debian, without having dependency issues. When we're able to ship properly tested support for modern Django, the description can be updated, but there otherwise wouldn't need to be any special changes made on your end (such as re-introducing the package).

**Comment by dionorgua** [comment]
Hi,
Yes, I know. I've actually tried to package ReviewBoard to Debian. And django-evolution was a dependency.

Sorry. I can't upload it without django dependency because debian archive accepts only source package that should be built automatically. And such packages should have all dependencies in "Depends" field.

In any case there is no django 1.6 in debian anymore, so users of django 1.6 in debian already needs to install django from sources/pip/virtualenv. In such case absence of django_evolution is not an issue for them at all.

I'll stay with option 2 for now and ask to remove django_evolution with URL to this bug report. 

Could you please keep it open (rename to something you like) and close once it's ready. I'll reintroduce it once it'll be ready!.

**Comment by chipx86** [comment]
Wayyyy longer than anyone would have wanted, but Django Evolution 2.0 will be coming out this week, and Review Board 4.0 with Django 1.11 support (since we're still obligated to support Python 2.7 installs for enterprises). That was a crazy amount of careful work, with nearly a full rewrite, but it' finally done.

I'm sure this is not on your radar anymore, but I can finally close this ticket :)
